apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
  labels:
    app: backend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-staging
  template:
    metadata:
      labels:
        app: backend-staging
    spec:
      containers:
      - name: backend
        image: saikotgirep/backend:main-INIT  # Jenkins will replace this with dynamic tag
        ports:
        - containerPort: 5000
